openapi: 3.0.3
info:
  title: API de Clientes, Trabajadores y Usuarios
  description: API para administrar clientes, trabajadores y usuarios
  version: 1.0.0

paths:
  /clientes/getAll:
    get:
      summary: Obtiene todas las personas
      description: Obtiene una lista de todas las personas.
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClienteResponse'

  /clientes/postCliente:
    post:
      summary: Crear una persona
      description: Crea una nueva persona.
      requestBody:
        description: Persona a crear
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClienteRequest'
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteResponse'

  /clientes/deleteCliente/{id}:
    delete:
      summary: Eliminar una persona
      description: Elimina una persona por su ID.
      parameters:
        - in: path
          name: id
          description: ID de la persona a eliminar
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteResponse'

  /clientes/updateCliente:
    put:
      summary: Actualizar una persona
      description: Actualiza una persona existente.
      requestBody:
        description: Persona a actualizar
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClienteRequest'
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/Persona'

  /trabajadores/getAll:
    get:
      summary: Obtiene todos los trabajadores
      description: Obtiene una lista de todos los trabajadores.
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TrabajadorResponse'

  /trabajadores/postTrabajador:
    post:
      summary: Crear un trabajador
      description: Crea un nuevo trabajador.
      requestBody:
        description: Trabajador a crear
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrabajadorRequest'
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrabajadorResponse'

  /trabajadores/updateTrabajador:
    put:
      summary: Actualizar un trabajador
      description: Actualiza un trabajador existente.
      requestBody:
        description: Trabajador a actualizar
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrabajadorRequest'
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/Trabajador'

  /trabajadores/deleteTrabajador/{id}:
    delete:
      summary: Eliminar un trabajador
      description: Elimina un trabajador por su ID.
      parameters:
        - in: path
          name: id
          description: ID del trabajador a eliminar
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrabajadorResponse'

  /usuarios/login:
    post:
      summary: Iniciar sesión
      description: Inicia sesión de usuario utilizando correo electrónico y contraseña.
      requestBody:
        description: Credenciales de inicio de sesión
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CredencialesLogin'
      responses:
        '200':
          description: Inicio de sesión exitoso
        '401':
          description: Credenciales incorrectas

components:
  schemas:
    TrabajadorRequest:
      type: object
      properties:
        nombre:
          type: string
          description: Nombre del trabajador
        apellido:
          type: string
          description: Apellido del trabajador
        email:
          type: string
          description: Correo electrónico del trabajador
        telefono:
          type: string
          description: Número de teléfono del trabajador
        id_cargo:
          type: integer
          description: Cargo del trabajador
        id_usuario:
          type: integer
          description: Usuario del trabajador
        id_tipo_doc:
          type: integer
          description: Tipo documento del trabajador
        nro_doc:
          type: integer
          description: Numero de documento del trabajador

    TrabajadorResponse:
      type: object
      properties:
        id:
          type: integer
          description: ID del trabajador
        nombre:
          type: string
          description: Nombre del trabajador
        apellido:
          type: string
          description: Apellido del trabajador
        email:
          type: string
          description: Correo electrónico del trabajador
        telefono:
          type: string
          description: Número de teléfono del trabajador
        id_cargo:
          type: integer
          description: Cargo del trabajador
        id_usuario:
          type: integer
          description: Usuario del trabajador
        id_tipo_doc:
          type: integer
          description: Tipo documento del trabajador
        nro_doc:
          type: integer
          description: Numero de documento del trabajador

    ClienteRequest:
      type: object
      properties:
        nombre:
          type: string
          description: Nombre del cliente
        apellido:
          type: string
          description: Apellido del cliente
        email:
          type: string
          description: Correo electrónico del cliente
        telefono:
          type: string
          description: Número de teléfono del cliente
        id_tipo_doc:
          type: string
          description: ID del tipo de documento del cliente
        nro_doc:
          type: integer
          description: Número de documento del cliente
        monotributo:
          type: string
          description: Monotributo del cliente
        id_tipo_cliente:
          type: integer
          description: ID del tipo del cliente
        id_tipo_categoria:
          type: integer
          description: ID del tipo de categoria
        cant_puntos:
          type: integer
          description: Cantidad de puntos de beneficios del cliente

    ClienteResponse:
      type: object
      properties:
        id:
          type: integer
          description: ID del cliente
        nombre:
          type: string
          description: Nombre del cliente
        apellido:
          type: string
          description: Apellido del cliente
        email:
          type: string
          description: Correo electrónico del cliente
        telefono:
          type: string
          description: Número de teléfono del cliente
        id_tipo_doc:
          type: string
          description: ID del tipo de documento del cliente
        nro_doc:
          type: integer
          description: Número de documento del cliente
        monotributo:
          type: string
          description: Monotributo del cliente
        id_tipo_cliente:
          type: integer
          description: ID del tipo de cliente
        id_tipo_categoria:
          type: integer
          description: ID del tipo de categoria
        cant_puntos:
          type: integer
          description: Cantidad de puntos de beneficios del cliente

    CredencialesLogin:
      type: object
      properties:
        nombre_usuario:
          type: string
          description: Nombre de usuario
        mail:
          type: string
          description: Correo electrónico del usuario
        password:
          type: string
          description: Contraseña del usuario

